// ─── Product Data ─────────────────────────────────────────────────────────
export const products = [
  {
    id: "legal",
    name: "IntelliForge Legal",
    slug: "legal",
    tagline: "AI-Powered Legal Intelligence",
    shortDesc:
      "Automate legal research, contract analysis, and case management with AI that thinks like a senior advocate.",
    icon: "⚖️",
    color: "from-blue-600 to-indigo-600",
    accentColor: "#6366f1",
    industry: "Legal",
    badge: "Legal Tech",
    heroFeature: "Draft contracts in minutes, not days",
    description:
      "IntelliForge Legal is a comprehensive AI platform designed specifically for law firms, solo practitioners, and in-house legal teams. It eliminates repetitive legal work so your team can focus on strategy, advocacy, and client relationships.",
    features: [
      "AI-powered legal research across case databases and statutes",
      "Automated contract drafting, review & risk flagging",
      "Smart case timeline and court date management",
      "Natural language legal query interface (ask in plain English)",
      "Precedent finder with jurisdiction-specific filters",
      "Client portal for document sharing and updates",
      "Automated billing and time tracking integration",
      "Compliance monitoring and regulatory alerts",
    ],
    useCases: [
      "Law firms handling high volumes of contracts",
      "Solo advocates managing their own research workflow",
      "Corporate legal departments automating compliance",
      "Court document preparation and filing automation",
      "Client onboarding and engagement letter automation",
    ],
    stats: [{ label: "Faster contract review", value: "80%" }, { label: "Research time saved", value: "70%" }, { label: "Billing accuracy", value: "99%" }],
  },
  {
    id: "studio",
    name: "IntelliForge Studio",
    slug: "studio",
    tagline: "AI for Film & Creative Production",
    shortDesc:
      "From script breakdown to final cut, AI tools that transform how film and media productions operate.",
    icon: "🎬",
    color: "from-rose-600 to-orange-500",
    accentColor: "#f43f5e",
    industry: "Film & Media",
    badge: "Media Tech",
    heroFeature: "Script-to-schedule in under 60 seconds",
    description:
      "IntelliForge Studio is the intelligent production management platform for film studios, independent producers, and advertising agencies. AI handles the complexity of production logistics so your creatives can stay creative.",
    features: [
      "AI script breakdown and automated shooting schedule",
      "Smart budget forecasting with AI scenario modeling",
      "Crew management with availability intelligence",
      "AI-powered VFX planning and resource allocation",
      "Digital asset tracking across departments",
      "Real-time production cost monitoring and alerts",
      "Talent management with deal memo automation",
      "Post-production workflow and milestone tracking",
    ],
    useCases: [
      "Feature film and web series production companies",
      "Independent filmmakers managing tight budgets",
      "Advertising agencies managing multiple shoots",
      "OTT content production houses",
      "Music video and commercial production studios",
    ],
    stats: [{ label: "Production cost reduction", value: "35%" }, { label: "Schedule accuracy", value: "92%" }, { label: "Time saved on admin", value: "65%" }],
  },
  {
    id: "fit",
    name: "IntelliForge Fit",
    slug: "fit",
    tagline: "Smart Fitness & Gym Management",
    shortDesc:
      "AI that predicts member churn, optimizes class schedules, and grows your fitness business on autopilot.",
    icon: "💪",
    color: "from-green-600 to-emerald-500",
    accentColor: "#10b981",
    industry: "Fitness",
    badge: "Fitness Tech",
    heroFeature: "Prevent member churn before it happens",
    description:
      "IntelliForge Fit gives gym owners and fitness studio operators a complete AI-powered command center. From member retention prediction to automated class scheduling — manage your entire fitness business intelligently.",
    features: [
      "AI churn prediction with 30-day early warning system",
      "Automated member onboarding and progress tracking",
      "Smart class scheduling based on demand patterns",
      "Trainer management with performance analytics",
      "AI-generated personalized workout and nutrition plans",
      "Automated billing, renewals, and EMI management",
      "Member engagement campaigns via SMS/WhatsApp/Email",
      "Revenue analytics and business intelligence dashboard",
    ],
    useCases: [
      "Multi-location gym chains and franchises",
      "Independent fitness studios and boutique gyms",
      "Yoga and wellness centers",
      "Corporate fitness programs",
      "Online fitness coaches managing member rosters",
    ],
    stats: [{ label: "Churn prediction accuracy", value: "87%" }, { label: "Revenue increase", value: "28%" }, { label: "Admin hours saved/month", value: "40hrs" }],
  },
  {
    id: "dine",
    name: "IntelliForge Dine",
    slug: "dine",
    tagline: "Restaurant Intelligence, Reimagined",
    shortDesc:
      "AI demand forecasting, smart menu pricing, and waste reduction for restaurants that want to run lean and profitable.",
    icon: "🍽️",
    color: "from-amber-500 to-orange-600",
    accentColor: "#f59e0b",
    industry: "Restaurants",
    badge: "F&B Tech",
    heroFeature: "Cut food waste by 40% in 90 days",
    description:
      "IntelliForge Dine is the AI-first restaurant management platform that helps F&B businesses maximize revenue while minimizing waste. Demand forecasting, dynamic pricing, staff scheduling — all powered by machine learning.",
    features: [
      "AI demand forecasting to optimize prep and purchasing",
      "Dynamic menu pricing based on demand and ingredients",
      "Intelligent table management and reservation optimization",
      "Staff scheduling with AI demand-based rostering",
      "Food waste analytics with AI reduction recommendations",
      "Customer sentiment analysis from reviews and feedback",
      "POS integration and real-time sales dashboards",
      "Supplier management and automated purchase orders",
    ],
    useCases: [
      "QSR and fast-casual restaurant chains",
      "Cloud kitchens and dark kitchen operators",
      "Fine dining restaurants and hotel F&B",
      "Café chains and beverage outlets",
      "Multi-brand food court operators",
    ],
    stats: [{ label: "Food waste reduction", value: "40%" }, { label: "Revenue per table increase", value: "22%" }, { label: "Order accuracy improvement", value: "95%" }],
  },
  {
    id: "pay",
    name: "IntelliForge Pay",
    slug: "pay",
    tagline: "Intelligent Payment Infrastructure",
    shortDesc:
      "AI-powered payment processing with real-time fraud detection, smart routing, and cash flow intelligence.",
    icon: "💳",
    color: "from-teal-600 to-cyan-500",
    accentColor: "#06b6d4",
    industry: "Finance",
    badge: "FinTech",
    heroFeature: "Fraud detected before it costs you",
    description:
      "IntelliForge Pay is an API-first, AI-powered payments platform designed for businesses that demand precision, security, and intelligence. Real-time fraud scoring, automated reconciliation, and cash flow forecasting built in.",
    features: [
      "Real-time AI fraud detection and risk scoring",
      "Smart payment routing for maximum success rates",
      "Multi-currency and multi-gateway support",
      "Automated reconciliation and accounting sync",
      "Cash flow forecasting with AI prediction models",
      "Instant payment analytics and business insights",
      "Split payments, subscriptions, and EMI automation",
      "Compliance and regulatory reporting automation",
    ],
    useCases: [
      "E-commerce and D2C brands processing high volumes",
      "SaaS companies managing subscriptions and renewals",
      "Marketplaces needing smart split payments",
      "Financial services firms requiring compliance automation",
      "Enterprise businesses with complex payment workflows",
    ],
    stats: [{ label: "Fraud reduction", value: "94%" }, { label: "Payment success rate", value: "99.2%" }, { label: "Reconciliation time saved", value: "85%" }],
  },
  {
    id: "inventory",
    name: "IntelliForge Inventory",
    slug: "inventory",
    tagline: "AI-Driven Supply Chain Intelligence",
    shortDesc:
      "Demand prediction, auto-reordering, and multi-warehouse intelligence that eliminates stockouts and overstock forever.",
    icon: "📦",
    color: "from-violet-600 to-purple-600",
    accentColor: "#8b5cf6",
    industry: "Logistics & Retail",
    badge: "Supply Chain",
    heroFeature: "Never stockout or overstock again",
    description:
      "IntelliForge Inventory uses machine learning to predict demand, automate procurement, and optimize stock levels across all your locations. Stop losing money on excess inventory and missed sales from stockouts.",
    features: [
      "ML demand forecasting with seasonal and trend modeling",
      "Automated smart reorder triggers and PO generation",
      "Multi-location and multi-warehouse management",
      "Barcode, QR code, and RFID tracking integration",
      "Supplier performance analytics and lead time tracking",
      "Dead stock and expiry management with AI alerts",
      "Real-time inventory dashboards and movement reports",
      "ERP, POS, and accounting system integrations",
    ],
    useCases: [
      "Retail chains with multiple store locations",
      "Manufacturing companies managing raw materials",
      "Healthcare organizations tracking medical supplies",
      "Pharmaceutical companies with expiry-critical inventory",
      "E-commerce businesses with high SKU counts",
    ],
    stats: [{ label: "Stockout reduction", value: "78%" }, { label: "Inventory carrying cost saved", value: "32%" }, { label: "Forecasting accuracy", value: "91%" }],
  },
  {
    id: "care",
    name: "IntelliForge Care",
    slug: "care",
    tagline: "AI Healthcare Management Platform",
    shortDesc:
      "Intelligent patient management, appointment optimization, and clinical workflow automation for modern healthcare providers.",
    icon: "🏥",
    color: "from-red-500 to-rose-600",
    accentColor: "#ef4444",
    industry: "Healthcare",
    badge: "Health Tech",
    heroFeature: "Zero missed appointments, optimal care",
    description:
      "IntelliForge Care is built for clinics, hospitals, and diagnostic centers that want to deliver better patient outcomes with fewer administrative burdens. AI handles scheduling, billing, and clinical coordination — your team handles care.",
    features: [
      "AI symptom pre-screening and triage prioritization",
      "Intelligent appointment scheduling and optimization",
      "Electronic Medical Records (EMR) management",
      "Automated medical billing and insurance claims",
      "Patient communication via WhatsApp and SMS",
      "Prescription management and pharmacy integration",
      "Lab result tracking and abnormal value alerts",
      "Patient portal for self-service booking and records",
    ],
    useCases: [
      "Multi-specialty clinics and polyclinics",
      "Diagnostic centers and radiology labs",
      "Specialty hospitals (dental, eye, orthopedic)",
      "Telemedicine and digital-first healthcare startups",
      "Corporate health programs and wellness clinics",
    ],
    stats: [{ label: "No-show rate reduction", value: "55%" }, { label: "Billing accuracy improvement", value: "97%" }, { label: "Staff time saved daily", value: "3hrs" }],
  },
  {
    id: "signals",
    name: "IntelliForge Signals",
    slug: "signals",
    tagline: "AI Market Intelligence & Trading Analytics",
    shortDesc:
      "Real-time AI trade signals, news sentiment analysis, and portfolio risk intelligence for modern traders and investors.",
    icon: "📈",
    color: "from-sky-600 to-blue-600",
    accentColor: "#3b82f6",
    industry: "Finance & Trading",
    badge: "FinTech",
    heroFeature: "Edge-based signals before the market moves",
    description:
      "IntelliForge Signals is an AI-powered market intelligence platform that processes thousands of data points per second — price action, news sentiment, macroeconomic indicators — to surface actionable trade signals and portfolio insights.",
    features: [
      "Real-time AI-generated buy/sell/hold signals",
      "NLP-powered news and social media sentiment analysis",
      "Portfolio risk scoring and drawdown alerts",
      "AI strategy backtesting with historical simulation",
      "Options chain analysis with AI probability models",
      "Macro indicator monitoring and market regime detection",
      "Custom alerting via Telegram, WhatsApp, and Email",
      "API access for algorithmic trading system integration",
    ],
    useCases: [
      "Retail traders seeking systematic, data-driven insights",
      "Investment advisors managing client portfolios",
      "Hedge funds and proprietary trading desks",
      "Wealth management firms building model portfolios",
      "Fintech startups building analytics-driven products",
    ],
    stats: [{ label: "Signal accuracy (backtested)", value: "74%" }, { label: "Data sources monitored", value: "500+" }, { label: "Latency", value: "<100ms" }],
  },
];

// ─── Industry Data ─────────────────────────────────────────────────────────
export const industries = [
  {
    id: "legal",
    name: "Legal",
    icon: "⚖️",
    description: "Empowering advocates, law firms, and legal departments with AI that handles research, contracts, and case management — so lawyers can focus on winning.",
    products: ["IntelliForge Legal"],
    pain: "Manual research, document overload, and billing inefficiencies are costing law firms thousands of hours annually.",
    solution: "IntelliForge Legal reduces research time by 70%, automates contract workflows, and delivers intelligent case management.",
    stats: ["70% research time saved", "80% faster contract drafting", "99% billing accuracy"],
    color: "from-blue-600/20 to-indigo-600/10",
    borderColor: "border-blue-600/20",
  },
  {
    id: "film",
    name: "Film & Media Production",
    icon: "🎬",
    description: "Helping film studios, independent producers, and content houses manage complex productions with AI-powered scheduling, budgeting, and crew coordination.",
    products: ["IntelliForge Studio"],
    pain: "Production overruns, budget surprises, and scheduling chaos are the #1 cause of project failure in film.",
    solution: "IntelliForge Studio uses AI to automate script breakdowns, forecast costs, and manage crew — keeping every production on time and on budget.",
    stats: ["35% cost reduction", "92% schedule accuracy", "65% less admin time"],
    color: "from-rose-600/20 to-orange-600/10",
    borderColor: "border-rose-600/20",
  },
  {
    id: "fitness",
    name: "Fitness & Wellness",
    icon: "💪",
    description: "Giving gym owners, yoga studios, and wellness centers AI tools to grow memberships, retain members, and scale operations without scaling headcount.",
    products: ["IntelliForge Fit"],
    pain: "Member churn is the silent killer of fitness businesses — most gyms lose 30%+ of their members annually.",
    solution: "IntelliForge Fit predicts churn 30 days in advance and triggers automated retention campaigns that actually work.",
    stats: ["87% churn prediction accuracy", "28% revenue growth", "40 hrs admin saved/month"],
    color: "from-green-600/20 to-emerald-600/10",
    borderColor: "border-green-600/20",
  },
  {
    id: "restaurants",
    name: "Restaurants & F&B",
    icon: "🍽️",
    description: "Enabling restaurants, cloud kitchens, and hotel F&B operations to maximize revenue, minimize waste, and deliver consistently excellent customer experiences.",
    products: ["IntelliForge Dine", "IntelliForge Inventory"],
    pain: "Food waste, staffing inefficiency, and unpredictable demand destroy restaurant margins every single day.",
    solution: "IntelliForge Dine and Inventory use AI demand forecasting to cut waste, optimize staffing, and maintain ideal stock levels.",
    stats: ["40% food waste reduction", "22% revenue per table increase", "95% order accuracy"],
    color: "from-amber-600/20 to-orange-600/10",
    borderColor: "border-amber-600/20",
  },
  {
    id: "healthcare",
    name: "Healthcare & Clinics",
    icon: "🏥",
    description: "Transforming how clinics, hospitals, and diagnostic centers operate — reducing administrative burden, improving patient experience, and enabling better clinical decisions.",
    products: ["IntelliForge Care", "IntelliForge Inventory"],
    pain: "Healthcare providers spend 40% of their time on administrative tasks instead of patient care — that's unsustainable.",
    solution: "IntelliForge Care automates scheduling, billing, EMR management, and patient communication so clinicians can focus on care.",
    stats: ["55% no-show reduction", "97% billing accuracy", "3 hrs/day saved per staff member"],
    color: "from-red-600/20 to-rose-600/10",
    borderColor: "border-red-600/20",
  },
  {
    id: "finance",
    name: "Finance & Trading",
    icon: "💰",
    description: "Equipping traders, investment advisors, and financial businesses with AI-powered signals, risk analytics, and payment infrastructure to stay competitive.",
    products: ["IntelliForge Signals", "IntelliForge Pay"],
    pain: "Information overload, slow payment processing, and rising fraud are costing financial businesses their competitive edge.",
    solution: "IntelliForge Signals delivers real-time market intelligence while IntelliForge Pay secures and optimizes every transaction.",
    stats: ["74% signal accuracy", "94% fraud reduction", "99.2% payment success rate"],
    color: "from-sky-600/20 to-blue-600/10",
    borderColor: "border-sky-600/20",
  },
];

// ─── Company Stats ─────────────────────────────────────────────────────────
export const companyStats = [
  { value: "8", label: "AI Products", suffix: "+" },
  { value: "6", label: "Industries Served", suffix: "+" },
  { value: "99.9", label: "Uptime SLA", suffix: "%" },
  { value: "256", label: "Bit Encryption", suffix: "-" },
];

// ─── Trust Signals ─────────────────────────────────────────────────────────
export const trustSignals = [
  { icon: "🛡️", label: "Enterprise-Grade Security", desc: "256-bit encryption, SOC 2 compliance" },
  { icon: "⚡", label: "99.9% Uptime SLA", desc: "Guaranteed availability with auto-failover" },
  { icon: "🔌", label: "API-First Architecture", desc: "Integrate with any existing system" },
  { icon: "📊", label: "Real-Time Analytics", desc: "Decisions backed by live data, not gut feel" },
  { icon: "🌐", label: "Multi-Tenant Ready", desc: "Scale from 1 user to 10,000 without friction" },
  { icon: "🤖", label: "Continuously Learning AI", desc: "Models improve with every interaction" },
];

// ─── Company Contact Info ──────────────────────────────────────────────────
export const companyInfo = {
  name: "IntelliForge Solutions",
  founder: "Praveen Kumar Yoganathan",
  email: "pooprav26@gmail.com",
  phone: "+91 8056497843",
  phoneDisplay: "+91 80564 97843",
  address: {
    street: "No 7, Nehru Street",
    area: "Veppampattu",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "602024",
    country: "India",
    full: "No 7, Nehru Street, Veppampattu, Chennai - 602024, Tamil Nadu, India",
  },
  hours: "Mon–Sat, 9:00 AM – 7:00 PM IST",
  website: "https://intelliforge-solutions.vercel.app",
  tagline: "Building Intelligent Systems for Every Industry",
};

// ─── Navigation Links ──────────────────────────────────────────────────────
export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/products" },
  { label: "Industries", href: "/industries" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
